### ISSUE TITLE
A non-template class definition is needed

### ISSUE THREAD

**Issue by shallow-shxu** [shihao-xu/MiniTutorialCPP#1]
The class template Stack is a great example. But for the newbees it's perhaps a litte difficult to get the whole point of it. I think i can add a non-template class into the source.

**Comment by shihao-xu** [comment]
I have already added you to the collaborator. You can from now on edit it, use appropriate label. @shallow-shxu

**Comment by shallow-shxu** [comment]
- [ ]#2 
- [ ]#3
